
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCT_FULL_FETCH_SUCCESS = 'PRODUCT_FULL_FETCH_SUCCESS';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCTS_FETCH_START = 'PRODUCTS_FETCH_START';
export const PRODUCTS_REFRESH_START = 'PRODUCTS_REFRESH_START';
export const PRODUCT_CATEGORIES_FETCH_SUCCESS = 'PRODUCT_CATEGORIES_FETCH_SUCCESS';
export const PRODUCT_ATTRIBUTE_SELECT = 'PRODUCT_ATTRIBUTE_SELECT';

export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const NAVIGATE_TO_PAGE = 'NAVIGATE_TO_PAGE';
